services:
     app:
       build:
         context: .
       volumes:
         - ./logs:/app/logs
         - ./results:/app/results
       ports:
         - "8501:8501"
       command:
         [
           "streamlit",
           "run",
           "src/app.py",
         ]

volumes:
  logs:
  results: